/**
 * fetch-videos.js — À lancer UNE SEULE FOIS en local
 *
 * Ce script interroge YouTube Data API pour chaque exercice (FR + EN),
 * puis réécrit data-fr.js et data-en.js avec les videoId hardcodés.
 *
 * Usage :
 *   node fetch-videos.js
 *
 * Prérequis :
 *   Node.js 18+ (fetch natif) ou Node 16 avec : npm install node-fetch
 */

const fs  = require('fs');
const path = require('path');

const YT_API_KEY = 'AIzaSyAitxZc5k36HZeXNa24fy-lwXL0kvYekpM';

// ─── Délai entre requêtes pour éviter le rate-limit ───────────────────────────
const DELAY_MS = 300;
const delay = ms => new Promise(r => setTimeout(r, ms));

// ─── Cherche le meilleur videoId YouTube vraiment embeddable ─────────────────
async function fetchVideoId(query) {

    // Étape 1 : chercher jusqu'à 5 candidats
    const searchUrl = `https://www.googleapis.com/youtube/v3/search`
        + `?part=snippet&type=video&videoEmbeddable=true&maxResults=5`
        + `&q=${encodeURIComponent(query)}&key=${YT_API_KEY}`;

    try {
        const searchRes  = await fetch(searchUrl);
        const searchJson = await searchRes.json();

        if (searchJson.error) {
            console.error(`  ✗ API error: ${searchJson.error.message}`);
            return null;
        }
        if (!searchJson.items || searchJson.items.length === 0) return null;

        const ids = searchJson.items.map(i => i.id.videoId).join(',');

        // Étape 2 : vérifier le vrai statut embeddable + public via videos endpoint
        const detailUrl = `https://www.googleapis.com/youtube/v3/videos`
            + `?part=status,contentDetails&id=${ids}&key=${YT_API_KEY}`;

        const detailRes  = await fetch(detailUrl);
        const detailJson = await detailRes.json();

        for (const video of (detailJson.items || [])) {
            const status = video.status;
            if (
                status.embeddable === true &&
                status.privacyStatus === 'public' &&
                status.uploadStatus === 'processed'
            ) {
                return video.id;
            }
        }

        // Aucun vraiment embeddable trouvé
        return null;

    } catch (e) {
        console.error(`  ✗ Fetch error: ${e.message}`);
        return null;
    }
}

// ─── Charge les données depuis les fichiers existants ────────────────────────
function loadData(filePath) {
    const code = fs.readFileSync(filePath, 'utf8');
    // Évalue le fichier JS pour récupérer l'objet dataFR ou dataEN
    const match = code.match(/^const\s+(data\w+)\s*=/m);
    if (!match) throw new Error(`Cannot find data variable in ${filePath}`);
    const varName = match[1];
    // Crée un contexte isolé
    const fn = new Function(`${code}; return ${varName};`);
    return { varName, data: fn() };
}

// ─── Génère le contenu JS d'un fichier data avec videoId intégrés ────────────
function serializeData(varName, data) {
    const lines = [];
    lines.push(`/* AUTO-GENERATED by fetch-videos.js — ne pas éditer manuellement */`);
    lines.push(`/* Les videoId YouTube sont hardcodés — relancer fetch-videos.js pour rafraîchir */\n`);
    lines.push(`const ${varName} = {`);

    // ui block
    lines.push(`    ui: {`);
    for (const [k, v] of Object.entries(data.ui)) {
        lines.push(`        ${k}: ${JSON.stringify(v)},`);
    }
    lines.push(`    },\n`);

    // intense block
    lines.push(`    intense: [`);
    for (const exo of data.intense) {
        const fields = [
            `name: ${JSON.stringify(exo.name)}`,
            `min: ${exo.min}`,
            `max: ${exo.max}`,
            `unit: ${JSON.stringify(exo.unit)}`,
            `emoji: ${JSON.stringify(exo.emoji)}`,
            `type: ${JSON.stringify(exo.type)}`,
        ];
        if (exo.desc)    fields.push(`desc: ${JSON.stringify(exo.desc)}`);
        if (exo.note)    fields.push(`note: ${JSON.stringify(exo.note)}`);
        if (exo.videoId) fields.push(`videoId: ${JSON.stringify(exo.videoId)}`);
        if (exo.img)     fields.push(`img: ${JSON.stringify(exo.img)}`);
        if (exo.svg)     fields.push(`svg: ${JSON.stringify(exo.svg)}`);
        lines.push(`        { ${fields.join(', ')} },`);
    }
    lines.push(`    ],\n`);

    // senior block
    lines.push(`    senior: [`);
    for (const exo of data.senior) {
        const fields = [
            `name: ${JSON.stringify(exo.name)}`,
            `min: ${exo.min}`,
            `max: ${exo.max}`,
            `unit: ${JSON.stringify(exo.unit)}`,
            `emoji: ${JSON.stringify(exo.emoji)}`,
            `type: ${JSON.stringify(exo.type)}`,
        ];
        if (exo.desc)    fields.push(`desc: ${JSON.stringify(exo.desc)}`);
        if (exo.note)    fields.push(`note: ${JSON.stringify(exo.note)}`);
        if (exo.videoId) fields.push(`videoId: ${JSON.stringify(exo.videoId)}`);
        if (exo.img)     fields.push(`img: ${JSON.stringify(exo.img)}`);
        if (exo.svg)     fields.push(`svg: ${JSON.stringify(exo.svg)}`);
        lines.push(`        { ${fields.join(', ')} },`);
    }
    lines.push(`    ],`);
    lines.push(`};`);

    return lines.join('\n');
}

// ─── Main ────────────────────────────────────────────────────────────────────
async function main() {
    const files = [
        { file: path.join(__dirname, 'js/data-fr.js'), lang: 'fr', mode: { intense: 'exercice', senior: 'senior' } },
        { file: path.join(__dirname, 'js/data-en.js'), lang: 'en', mode: { intense: 'workout',  senior: 'senior exercise' } },
    ];

    for (const { file, lang, mode } of files) {
        console.log(`\n════════════════════════════════`);
        console.log(`🌍 Processing ${lang.toUpperCase()} — ${file}`);
        console.log(`════════════════════════════════`);

        const { varName, data } = loadData(file);
        let total = 0, found = 0;

        for (const section of ['intense', 'senior']) {
            console.log(`\n  📂 Section: ${section}`);
            for (const exo of data[section]) {
                total++;
                const suffix = section === 'intense' ? mode.intense : mode.senior;
                const query  = lang === 'fr'
                    ? `comment faire ${exo.name} ${suffix}`
                    : `how to do ${exo.name} ${suffix}`;

                process.stdout.write(`  [${total}] ${exo.name} ... `);

                // Skip if already has a videoId
                if (exo.videoId) {
                    found++;
                    console.log(`⏭ skipped (already exists)`);
                    continue;
                }

                const videoId = await fetchVideoId(query);

                if (videoId) {
                    exo.videoId = videoId;
                    found++;
                    console.log(`✓ ${videoId}`);
                } else {
                    console.log(`✗ not found`);
                }

                await delay(DELAY_MS);
            }
        }

        // Réécriture du fichier
        const output = serializeData(varName, data);
        fs.writeFileSync(file, output, 'utf8');
        console.log(`\n  ✅ ${found}/${total} videos found — ${file} updated`);
    }

    console.log(`\n🎉 Done! Reload your browser to test.`);
}

main().catch(console.error);
